"""empty message

Revision ID: 0b63332a8d83
Revises: 2db65b421b62
Create Date: 2024-09-13 14:34:54.826804

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b63332a8d83"
down_revision: Union[str, None] = "2db65b421b62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "donnees_point_de_prelevement_aep_zre",
        sa.Column(
            "prelevement_realise",
            sa.Boolean(),
            nullable=True,
            comment="Indique si un prélèvement a été réalisé",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "declaration_plusieurs_mois_camion_citerne",
            sa.Boolean(),
            nullable=True,
            comment="Indique si la déclaration concerne plusieurs mois (seules les régularisations peuvent faire l'objet d'une déclaration portant sur plusieurs mois)",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "mois_debut_declaration_camion_citerne",
            sa.String(),
            nullable=True,
            comment="Mois de début de déclaration pour les AOT de camions citernes",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "mois_fin_declaration_camion_citerne",
            sa.String(),
            nullable=True,
            comment="Mois de fin de déclaration pour les AOT de camions citernes",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "mois_declaration_camion_citerne",
            sa.String(),
            nullable=True,
            comment="Mois de déclaration pour les AOT de camions citernes",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "volumes_pompes_tableau_suivi_camion_citerne",
            sa.Boolean(),
            nullable=True,
            comment="Indique si les volumes pompés sont renseignés dans un tableau de suivi pour les AOT de camions citernes",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dossier", "volumes_pompes_tableau_suivi_camion_citerne")
    op.drop_column("dossier", "mois_declaration_camion_citerne")
    op.drop_column("dossier", "mois_fin_declaration_camion_citerne")
    op.drop_column("dossier", "mois_debut_declaration_camion_citerne")
    op.drop_column("dossier", "declaration_plusieurs_mois_camion_citerne")
    op.drop_column("donnees_point_de_prelevement_aep_zre", "prelevement_realise")
    # ### end Alembic commands ###
