"""empty message

Revision ID: 14c947b4d8f8
Revises: b0cbb7dd97ef
Create Date: 2024-05-30 03:22:03.042578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14c947b4d8f8'
down_revision: Union[str, None] = 'b0cbb7dd97ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossier_fichier_tableau_suivi_camion_citerne_assoc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('dossier_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('piece_jointe_id', postgresql.UUID(as_uuid=True), nullable=False, comment='La clé primaire de la piece jointe'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ),
    sa.ForeignKeyConstraint(['piece_jointe_id'], ['piece_jointe.id'], ),
    sa.PrimaryKeyConstraint('id', 'dossier_id', 'piece_jointe_id')
    )
    op.create_index(op.f('ix_dossier_fichier_tableau_suivi_camion_citerne_assoc_date_created'), 'dossier_fichier_tableau_suivi_camion_citerne_assoc', ['date_created'], unique=False)
    op.alter_column('avis', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.alter_column('avis', 'id_avis',
               existing_type=sa.VARCHAR(),
               comment="Identifiant unique de l'avis",
               existing_nullable=True)
    op.alter_column('avis', 'question',
               existing_type=sa.VARCHAR(),
               comment='Question de l’instructeur',
               existing_nullable=True)
    op.alter_column('avis', 'reponse',
               existing_type=sa.VARCHAR(),
               comment='Réponse de l’expert',
               existing_nullable=True)
    op.alter_column('avis', 'date_question',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de la question',
               existing_nullable=True)
    op.alter_column('avis', 'date_reponse',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de la reponse',
               existing_nullable=True)
    op.alter_column('avis', 'claimant_email',
               existing_type=sa.VARCHAR(),
               comment='Email du claimant',
               existing_nullable=True)
    op.alter_column('avis', 'expert_email',
               existing_type=sa.VARCHAR(),
               comment="Email de l'expert",
               existing_nullable=True)
    op.alter_column('avis_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('demarche_data_brute', 'hashed_collected_data',
               existing_type=sa.VARCHAR(),
               comment='Le hash du fichier de snapshot.',
               existing_nullable=True)
    op.alter_column('demarche_data_brute', 'object_storage_key',
               existing_type=sa.VARCHAR(),
               comment='La cle du fichier de snapshot dans le bucket.',
               existing_nullable=True)
    op.alter_column('donnees_point_de_prelevement', 'ligne',
               existing_type=sa.INTEGER(),
               comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.alter_column('donnees_point_de_prelevement', 'nom_point_prelevement',
               existing_type=sa.VARCHAR(),
               comment='Nom du point de prélèvement',
               existing_nullable=True)
    op.add_column('dossier', sa.Column('numero_telephone_declarant', sa.String(), nullable=True, comment='Numéro de téléphone du déclarant'))
    op.alter_column('dossier', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment='Identifiant unique du dossier.',
               existing_nullable=True)
    op.alter_column('dossier', 'adresse_email_connexion',
               existing_type=sa.VARCHAR(),
               comment='Email de connexion associé au compte Démarches simplifiées du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'civilite_declarant',
               existing_type=sa.VARCHAR(),
               comment='Civilité du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'nom_declarant',
               existing_type=sa.VARCHAR(),
               comment='Nom du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'prenom_declarant',
               existing_type=sa.VARCHAR(),
               comment='Prénom du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'depot_pour_mandataire',
               existing_type=sa.BOOLEAN(),
               comment='Indique si le déclarant dépose pour un mantataire',
               existing_nullable=True)
    op.alter_column('dossier', 'nom_mandataire',
               existing_type=sa.VARCHAR(),
               comment='Nom du mandataire',
               existing_nullable=True)
    op.alter_column('dossier', 'prenom_mandataire',
               existing_type=sa.VARCHAR(),
               comment='Prénom du mandataire',
               existing_nullable=True)
    op.alter_column('dossier', 'archive',
               existing_type=sa.BOOLEAN(),
               comment='Indique si le dossier est archivé',
               existing_nullable=True)
    op.alter_column('dossier', 'etat_dossier',
               existing_type=sa.VARCHAR(),
               comment='Etat d’avancement du dossier',
               existing_nullable=True)
    op.alter_column('dossier', 'derniere_mise_a_jour',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de dernière mise à jour du dossier (notamment les avis, la messagerie…)',
               existing_nullable=True)
    op.alter_column('dossier', 'date_depot',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de dépôt du dossier',
               existing_nullable=True)
    op.alter_column('dossier', 'date_passage_instruction',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de passage en instruction',
               existing_nullable=True)
    op.alter_column('dossier', 'date_traitement',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de traitement par l’instructeur',
               existing_nullable=True)
    op.alter_column('dossier', 'motivation_decision',
               existing_type=sa.VARCHAR(),
               comment='Motivation de la décision par l’instructeur',
               existing_nullable=True)
    op.alter_column('dossier', 'instructeurs',
               existing_type=sa.VARCHAR(),
               comment='Instructeurs affectés à la démarche',
               existing_nullable=True)
    op.alter_column('dossier', 'groupe_instructeur',
               existing_type=sa.VARCHAR(),
               comment='Groupe d’instructeurs affecté à la démarche',
               existing_nullable=True)
    op.alter_column('dossier', 'adresse_email_declarant',
               existing_type=sa.VARCHAR(),
               comment='Adresse email du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'statut_declarant',
               existing_type=sa.VARCHAR(),
               comment='Statut du déclarant (particulier ou représentant d’une structure)',
               existing_nullable=True)
    op.alter_column('dossier', 'raison_sociale_structure',
               existing_type=sa.VARCHAR(),
               comment='Raison sociale de la structure',
               existing_nullable=True)
    op.alter_column('dossier', 'type_prelevement',
               existing_type=sa.VARCHAR(),
               comment='Type de prélèvement',
               existing_nullable=True)
    op.alter_column('dossier', 'numero_arrete_aot',
               existing_type=sa.VARCHAR(),
               comment='Numéro de l’arrêté préfectoral d’AOT',
               existing_nullable=True)
    op.alter_column('dossier', 'mode_transmission_donnees_camion_citerne',
               existing_type=sa.VARCHAR(),
               comment='Mode de transmission des données pour les AOT camion citerne (une à une, ou au format tableur)',
               existing_nullable=True)
    op.alter_column('dossier', 'commentaire',
               existing_type=sa.VARCHAR(),
               comment='Commentaire libre du déclarant sur la déclaration',
               existing_nullable=True)
    op.alter_column('dossier', 'numero_serie_compteur',
               existing_type=sa.VARCHAR(),
               comment='Numéro de série du compteur (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'validation_informations',
               existing_type=sa.BOOLEAN(),
               comment='Déclaration par le préleveur que les informations sont exactes',
               existing_nullable=True)
    op.alter_column('dossier', 'donnees_compteur_volumetrique',
               existing_type=sa.BOOLEAN(),
               comment='Indique sur les données sont issues d’un compteur volumétrique (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'compteur_lecture_directe',
               existing_type=sa.BOOLEAN(),
               comment='Indique s’il s’agit d’un compteur à lecture directe (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'panne_compteur',
               existing_type=sa.BOOLEAN(),
               comment='Indique si une panne ou un changement de compteur est déclarée (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'prelevement_sur_periode_camion_citerne',
               existing_type=sa.BOOLEAN(),
               comment='Pour les AOT de camions citernes, indique si des prélèvements ont été réalisés sur la période concernée par la déclaration (mois précédent)',
               existing_nullable=True)
    op.alter_column('dossier', 'date_debut_periode_declaree',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date du début de la période concernée par la déclaration',
               existing_nullable=True)
    op.alter_column('dossier', 'date_fin_periode_declaree',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de fin de la période concernée par la déclaration',
               existing_nullable=True)
    op.alter_column('dossier', 'annee_prelevement_camion_citerne',
               existing_type=sa.INTEGER(),
               comment='Pour les camions citernes, année de prélèvement (permet de définir le niveau de précision attendu dans la déclaration)',
               existing_nullable=True)
    op.drop_column('dossier', 'numero_telephone')
    op.alter_column('extrait_de_registre', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.alter_column('extrait_de_registre', 'ligne',
               existing_type=sa.INTEGER(),
               comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.alter_column('extraits_de_registres_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('fichiers_autres_documents_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('fichiers_tableurs_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('message', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.alter_column('message', 'id_message',
               existing_type=sa.VARCHAR(),
               comment='Identifiant unique du messge dans demarches simplifiees',
               existing_nullable=True)
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(),
               comment='Email contacté',
               existing_nullable=True)
    op.alter_column('message', 'body',
               existing_type=sa.VARCHAR(),
               comment='Corps du message',
               existing_nullable=True)
    op.alter_column('message', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date de reception du message',
               existing_nullable=True)
    op.alter_column('message_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.add_column('piece_jointe', sa.Column('demarches_simplifiees_url', sa.String(), nullable=True, comment="l'URL sur demarches simplifiees"))
    op.alter_column('piece_jointe', 'checksum',
               existing_type=sa.VARCHAR(),
               comment='Checksum du fichier.',
               existing_nullable=True)
    op.alter_column('piece_jointe', 'type_fichier',
               existing_type=sa.VARCHAR(),
               comment='Le type MIME du fichier.',
               existing_nullable=True)
    op.alter_column('piece_jointe', 'nom_fichier',
               existing_type=sa.VARCHAR(),
               comment='Le nom du fichier.',
               existing_nullable=True)
    op.alter_column('piece_jointe', 'object_storage_key',
               existing_type=sa.VARCHAR(),
               comment='La cle du fichier dans le bucket.',
               existing_nullable=True)
    op.drop_column('piece_jointe', 'demande_simplifiees_url')
    op.alter_column('releve_index', 'ligne',
               existing_type=sa.INTEGER(),
               comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'ligne',
               existing_type=sa.INTEGER(),
               comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'point_prelevement_camion_citerne',
               existing_type=sa.VARCHAR(),
               comment='Point de prélèvement pour le camion citerne',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'annee_prelevement_camion_citerne_2',
               existing_type=sa.INTEGER(),
               comment='Année à laquelle le volume prélevé est associé (pour les prélèvements antérieurs à 2024, on accepte un chiffre globalisé à l’année)',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'volumes_pompes_camions_citernes',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='Volumes pompés par les camions citernes (en m³), pour les déclarants ayant voulu déclarer leurs données une à une',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'date_prelevement_camion_citerne',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date précise de prélèvement par camion citerne',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volumes_pompes', 'date_prelevement_camion_citerne',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date précise de prélèvement par camion citerne',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'volumes_pompes_camions_citernes',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Volumes pompés par les camions citernes (en m³), pour les déclarants ayant voulu déclarer leurs données une à une',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'annee_prelevement_camion_citerne_2',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Année à laquelle le volume prélevé est associé (pour les prélèvements antérieurs à 2024, on accepte un chiffre globalisé à l’année)',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'point_prelevement_camion_citerne',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Point de prélèvement pour le camion citerne',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'ligne',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.alter_column('volumes_pompes', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.alter_column('releve_index', 'ligne',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.add_column('piece_jointe', sa.Column('demande_simplifiees_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('piece_jointe', 'object_storage_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='La cle du fichier dans le bucket.',
               existing_nullable=True)
    op.alter_column('piece_jointe', 'nom_fichier',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Le nom du fichier.',
               existing_nullable=True)
    op.alter_column('piece_jointe', 'type_fichier',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Le type MIME du fichier.',
               existing_nullable=True)
    op.alter_column('piece_jointe', 'checksum',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Checksum du fichier.',
               existing_nullable=True)
    op.drop_column('piece_jointe', 'demarches_simplifiees_url')
    op.alter_column('message_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('message', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de reception du message',
               existing_nullable=True)
    op.alter_column('message', 'body',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Corps du message',
               existing_nullable=True)
    op.alter_column('message', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Email contacté',
               existing_nullable=True)
    op.alter_column('message', 'id_message',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Identifiant unique du messge dans demarches simplifiees',
               existing_nullable=True)
    op.alter_column('message', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.alter_column('fichiers_tableurs_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('fichiers_autres_documents_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('extraits_de_registres_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('extrait_de_registre', 'ligne',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.alter_column('extrait_de_registre', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.add_column('dossier', sa.Column('numero_telephone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('dossier', 'annee_prelevement_camion_citerne',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Pour les camions citernes, année de prélèvement (permet de définir le niveau de précision attendu dans la déclaration)',
               existing_nullable=True)
    op.alter_column('dossier', 'date_fin_periode_declaree',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de fin de la période concernée par la déclaration',
               existing_nullable=True)
    op.alter_column('dossier', 'date_debut_periode_declaree',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date du début de la période concernée par la déclaration',
               existing_nullable=True)
    op.alter_column('dossier', 'prelevement_sur_periode_camion_citerne',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Pour les AOT de camions citernes, indique si des prélèvements ont été réalisés sur la période concernée par la déclaration (mois précédent)',
               existing_nullable=True)
    op.alter_column('dossier', 'panne_compteur',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indique si une panne ou un changement de compteur est déclarée (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'compteur_lecture_directe',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indique s’il s’agit d’un compteur à lecture directe (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'donnees_compteur_volumetrique',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indique sur les données sont issues d’un compteur volumétrique (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'validation_informations',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Déclaration par le préleveur que les informations sont exactes',
               existing_nullable=True)
    op.alter_column('dossier', 'numero_serie_compteur',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Numéro de série du compteur (pour les AOT agricoles)',
               existing_nullable=True)
    op.alter_column('dossier', 'commentaire',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Commentaire libre du déclarant sur la déclaration',
               existing_nullable=True)
    op.alter_column('dossier', 'mode_transmission_donnees_camion_citerne',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Mode de transmission des données pour les AOT camion citerne (une à une, ou au format tableur)',
               existing_nullable=True)
    op.alter_column('dossier', 'numero_arrete_aot',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Numéro de l’arrêté préfectoral d’AOT',
               existing_nullable=True)
    op.alter_column('dossier', 'type_prelevement',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Type de prélèvement',
               existing_nullable=True)
    op.alter_column('dossier', 'raison_sociale_structure',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Raison sociale de la structure',
               existing_nullable=True)
    op.alter_column('dossier', 'statut_declarant',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Statut du déclarant (particulier ou représentant d’une structure)',
               existing_nullable=True)
    op.alter_column('dossier', 'adresse_email_declarant',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Adresse email du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'groupe_instructeur',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Groupe d’instructeurs affecté à la démarche',
               existing_nullable=True)
    op.alter_column('dossier', 'instructeurs',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Instructeurs affectés à la démarche',
               existing_nullable=True)
    op.alter_column('dossier', 'motivation_decision',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Motivation de la décision par l’instructeur',
               existing_nullable=True)
    op.alter_column('dossier', 'date_traitement',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de traitement par l’instructeur',
               existing_nullable=True)
    op.alter_column('dossier', 'date_passage_instruction',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de passage en instruction',
               existing_nullable=True)
    op.alter_column('dossier', 'date_depot',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de dépôt du dossier',
               existing_nullable=True)
    op.alter_column('dossier', 'derniere_mise_a_jour',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de dernière mise à jour du dossier (notamment les avis, la messagerie…)',
               existing_nullable=True)
    op.alter_column('dossier', 'etat_dossier',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Etat d’avancement du dossier',
               existing_nullable=True)
    op.alter_column('dossier', 'archive',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indique si le dossier est archivé',
               existing_nullable=True)
    op.alter_column('dossier', 'prenom_mandataire',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Prénom du mandataire',
               existing_nullable=True)
    op.alter_column('dossier', 'nom_mandataire',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Nom du mandataire',
               existing_nullable=True)
    op.alter_column('dossier', 'depot_pour_mandataire',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indique si le déclarant dépose pour un mantataire',
               existing_nullable=True)
    op.alter_column('dossier', 'prenom_declarant',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Prénom du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'nom_declarant',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Nom du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'civilite_declarant',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Civilité du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'adresse_email_connexion',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Email de connexion associé au compte Démarches simplifiées du déclarant',
               existing_nullable=True)
    op.alter_column('dossier', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identifiant unique du dossier.',
               existing_nullable=True)
    op.drop_column('dossier', 'numero_telephone_declarant')
    op.alter_column('donnees_point_de_prelevement', 'nom_point_prelevement',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Nom du point de prélèvement',
               existing_nullable=True)
    op.alter_column('donnees_point_de_prelevement', 'ligne',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ordre dans lequel l’index a été déclaré pour une même déclaration',
               existing_nullable=True)
    op.alter_column('demarche_data_brute', 'object_storage_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='La cle du fichier de snapshot dans le bucket.',
               existing_nullable=True)
    op.alter_column('demarche_data_brute', 'hashed_collected_data',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Le hash du fichier de snapshot.',
               existing_nullable=True)
    op.alter_column('avis_assoc', 'piece_jointe_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='La clé primaire de la piece jointe',
               existing_nullable=False)
    op.alter_column('avis', 'expert_email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Email de l'expert",
               existing_nullable=True)
    op.alter_column('avis', 'claimant_email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Email du claimant',
               existing_nullable=True)
    op.alter_column('avis', 'date_reponse',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de la reponse',
               existing_nullable=True)
    op.alter_column('avis', 'date_question',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date de la question',
               existing_nullable=True)
    op.alter_column('avis', 'reponse',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Réponse de l’expert',
               existing_nullable=True)
    op.alter_column('avis', 'question',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Question de l’instructeur',
               existing_nullable=True)
    op.alter_column('avis', 'id_avis',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Identifiant unique de l'avis",
               existing_nullable=True)
    op.alter_column('avis', 'id_dossier',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identifiant unique du dossier',
               existing_nullable=True)
    op.drop_index(op.f('ix_dossier_fichier_tableau_suivi_camion_citerne_assoc_date_created'), table_name='dossier_fichier_tableau_suivi_camion_citerne_assoc')
    op.drop_table('dossier_fichier_tableau_suivi_camion_citerne_assoc')
    # ### end Alembic commands ###
