"""empty message

Revision ID: 151830e21f48
Revises: 944b3db2e00d
Create Date: 2024-07-18 01:56:01.917569

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "151830e21f48"
down_revision: Union[str, None] = "944b3db2e00d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error_mail",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column(
            "id_dossier",
            sa.Integer(),
            nullable=True,
            comment="Identifiant unique du dossier.",
        ),
        sa.Column(
            "email", sa.String(), nullable=True, comment="Adresse email du déclarant"
        ),
        sa.Column("message", sa.String(), nullable=True, comment="Message d'erreur"),
        sa.Column(
            "is_sent",
            sa.Boolean(),
            nullable=True,
            comment="Indique si l'erreur a été envoyée par email",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_error_mail_date_created"), "error_mail", ["date_created"], unique=False
    )
    op.create_index(
        op.f("ix_error_mail_id_dossier"), "error_mail", ["id_dossier"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_error_mail_id_dossier"), table_name="error_mail")
    op.drop_index(op.f("ix_error_mail_date_created"), table_name="error_mail")
    op.drop_table("error_mail")
    # ### end Alembic commands ###
