"""empty message

Revision ID: 2db65b421b62
Revises: 0ba8f601851e
Create Date: 2024-09-03 18:12:50.377482

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2db65b421b62"
down_revision: Union[str, None] = "0ba8f601851e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dossier", "developpement_interface_visualisation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dossier",
        sa.Column(
            "developpement_interface_visualisation",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Si vous le souhaitez, vous pouvez nous faire part des informations que vous aimeriez voir figurer dans cet outil de visualisation de données, et qui pourraient vous être utiles pour mieux suivre vos prélèvements au fil du temps.",
        ),
    )
    # ### end Alembic commands ###
