"""empty message

Revision ID: 46bce3f2f1e2
Revises: 151830e21f48
Create Date: 2024-08-12 17:43:52.322609

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46bce3f2f1e2"
down_revision: Union[str, None] = "151830e21f48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "error_mail",
        sa.Column(
            "demarche_data_brute_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
    )
    op.create_foreign_key(
        None, "error_mail", "demarche_data_brute", ["demarche_data_brute_id"], ["id"]
    )
    op.drop_column("error_mail", "is_sent")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "error_mail",
        sa.Column(
            "is_sent",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
            comment="Indique si l'erreur a été envoyée par email",
        ),
    )
    op.drop_constraint(None, "error_mail", type_="foreignkey")
    op.drop_column("error_mail", "demarche_data_brute_id")
    # ### end Alembic commands ###
