"""empty message

Revision ID: 7385df688e7d
Revises: 680800074590
Create Date: 2024-07-11 01:08:26.999909

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7385df688e7d"
down_revision: Union[str, None] = "680800074590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_demarche_data_brute_id"), "demarche_data_brute", ["id"], unique=False
    )
    op.add_column(
        "dossier",
        sa.Column(
            "prelevement_points_autorises_aot_2023",
            sa.Boolean(),
            nullable=True,
            comment="Avez-vous prélevé sur au moins un des points autorisés par votre AOT durant l'année 2023 ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "rappel_obligation_mensuelle_declaration",
            sa.Boolean(),
            nullable=True,
            comment="Souhaiteriez-vous recevoir le 1er de chaque mois un mail vous rappelant l'obligation mensuelle de déclaration ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "acceptation_contact_deal",
            sa.Boolean(),
            nullable=True,
            comment="Accepteriez-vous d’être recontacté.e par la DEAL pour échanger davantage sur le sujet ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "mois_prelevement_camion_citerne",
            sa.String(),
            nullable=True,
            comment="En quel mois les prélèvements que vous allez déclarer ont-ils été réalisés ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "note_facilite_utilisation",
            sa.String(),
            nullable=True,
            comment="Donnez une note sur la facilité de prise en main de l’outil démarches simplifiées",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "remarque_note",
            sa.String(),
            nullable=True,
            comment="Souhaitez-vous apporter une remarque à cette note ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "temps_remplissage_questionnaire",
            sa.String(),
            nullable=True,
            comment="Combien de temps avez-vous passé à remplir ce questionnaire ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "amelioration_temps_remplissage",
            sa.String(),
            nullable=True,
            comment="Avez-vous une idée ce que qui pourrait être amélioré pour réduire ce temps ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "temps_formatage_donnees",
            sa.String(),
            nullable=True,
            comment="Combien de temps avez-vous passé au formatage des données (utilisation du modèle de tableur imposé) ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "televersement_tableur_brutes",
            sa.String(),
            nullable=True,
            comment="Qui est la personne qui a téléversé le tableur de données brutes dans l’outil Démarches Simplifiées ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "acces_formulaire",
            sa.String(),
            nullable=True,
            comment="Comment cette personne a-t-elle eu accès au formulaire ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "declarant_demarche_simplifiee",
            sa.String(),
            nullable=True,
            comment="Qui est la personne qui a fait la déclaration sur Démarches Simplifiées ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "raison_non_declaration_preleveur",
            sa.String(),
            nullable=True,
            comment="Pour quelles raisons la personne en charge du prélèvement n'a-t-elle pas pu faire la déclaration elle-même ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "demande_documentation",
            sa.String(),
            nullable=True,
            comment="Souhaiteriez-vous disposer d’une documentation sur le remplissage de ce formulaire et la façon de remplir le modèle de tableau de données ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "amelioration_documentation",
            sa.String(),
            nullable=True,
            comment="Sous quelle forme une documentation d’utilisation vous semble la plus utile ?",
        ),
    )
    op.add_column(
        "dossier",
        sa.Column(
            "suggestion_informations_visualisation",
            sa.String(),
            nullable=True,
            comment="Si vous le souhaitez, vous pouvez nous faire part des informations que vous aimeriez voir figurer dans cet outil de visualisation de données, "
            + "et qui pourraient vous être utiles pour mieux suivre vos prélèvements au fil du temps.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dossier", "suggestion_informations_visualisation")
    op.drop_column("dossier", "amelioration_documentation")
    op.drop_column("dossier", "demande_documentation")
    op.drop_column("dossier", "raison_non_declaration_preleveur")
    op.drop_column("dossier", "declarant_demarche_simplifiee")
    op.drop_column("dossier", "acces_formulaire")
    op.drop_column("dossier", "televersement_tableur_brutes")
    op.drop_column("dossier", "temps_formatage_donnees")
    op.drop_column("dossier", "amelioration_temps_remplissage")
    op.drop_column("dossier", "temps_remplissage_questionnaire")
    op.drop_column("dossier", "remarque_note")
    op.drop_column("dossier", "note_facilite_utilisation")
    op.drop_column("dossier", "mois_prelevement_camion_citerne")
    op.drop_column("dossier", "acceptation_contact_deal")
    op.drop_column("dossier", "rappel_obligation_mensuelle_declaration")
    op.drop_column("dossier", "prelevement_points_autorises_aot_2023")
    op.drop_index(op.f("ix_demarche_data_brute_id"), table_name="demarche_data_brute")
    # ### end Alembic commands ###
