"""empty message

Revision ID: 81d6069e8d21
Revises: d35ec545c72b
Create Date: 2024-08-15 17:07:26.547677

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81d6069e8d21"
down_revision: Union[str, None] = "d35ec545c72b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prelevement_releve",
        sa.Column(
            "remarque_serie_donnees",
            sa.String(),
            nullable=True,
            comment="Remarque sur la série de données",
        ),
    )
    op.add_column(
        "prelevement_releve_last_snapshot",
        sa.Column(
            "remarque_serie_donnees",
            sa.String(),
            nullable=True,
            comment="Remarque sur la série de données",
        ),
        schema="demarches_simplifiees_last_snapshot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "prelevement_releve_last_snapshot",
        "remarque_serie_donnees",
        schema="demarches_simplifiees_last_snapshot",
    )
    op.drop_column("prelevement_releve", "remarque_serie_donnees")
    # ### end Alembic commands ###
