"""empty message

Revision ID: ae152d7b59a7
Revises: d8a41ba6649a
Create Date: 2024-07-15 00:11:46.853081

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae152d7b59a7"
down_revision: Union[str, None] = "d8a41ba6649a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dossier_fichier_tableau_suivi_camion_citerne_assoc_ls",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("dossier_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "piece_jointe_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment="La clé primaire de la piece jointe",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossier_last_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["piece_jointe_id"],
            ["piece_jointe_last_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id", "dossier_id", "piece_jointe_id"),
    )
    op.create_index(
        op.f("ix_dossier_fichier_tableau_suivi_camion_citerne_assoc_ls_date_created"),
        "dossier_fichier_tableau_suivi_camion_citerne_assoc_ls",
        ["date_created"],
        unique=False,
    )
    op.drop_index(
        "ix_dossier_fichier_tableau_suivi_camion_citerne_assoc_l_c63e",
        table_name="dossier_fichier_tableau_suivi_camion_citerne_assoc_last_snapsho",
    )
    op.drop_table("dossier_fichier_tableau_suivi_camion_citerne_assoc_last_snapsho")
    op.alter_column(
        "dossier_last_snapshot",
        "suggestion_informations_visualisation",
        existing_type=sa.VARCHAR(),
        comment="Si vous le souhaitez, vous pouvez nous faire part des informations que vous aimeriez voir figurer dans cet outil de visualisation de données, et qui pourraient vous être utiles pour mieux suivre vos prélèvements au fil du temps.",
        existing_comment="Si vous le souhaitez, vous pouvez nous faire part des informations que vous aimeriez voir figurer dans cet outil de visualisation de données,et qui pourraient vous être utiles pour mieux suivre vos prélèvements au fil du temps.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dossier_last_snapshot",
        "suggestion_informations_visualisation",
        existing_type=sa.VARCHAR(),
        comment="Si vous le souhaitez, vous pouvez nous faire part des informations que vous aimeriez voir figurer dans cet outil de visualisation de données,et qui pourraient vous être utiles pour mieux suivre vos prélèvements au fil du temps.",
        existing_comment="Si vous le souhaitez, vous pouvez nous faire part des informations que vous aimeriez voir figurer dans cet outil de visualisation de données, et qui pourraient vous être utiles pour mieux suivre vos prélèvements au fil du temps.",
        existing_nullable=True,
    )
    op.create_table(
        "dossier_fichier_tableau_suivi_camion_citerne_assoc_last_snapsho",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "date_created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("dossier_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "piece_jointe_id",
            postgresql.UUID(),
            autoincrement=False,
            nullable=False,
            comment="La clé primaire de la piece jointe",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["dossier_last_snapshot.id"],
            name="dossier_fichier_tableau_suivi_camion_citerne_a_dossier_id_fkey1",
        ),
        sa.ForeignKeyConstraint(
            ["piece_jointe_id"],
            ["piece_jointe_last_snapshot.id"],
            name="dossier_fichier_tableau_suivi_camion_cite_piece_jointe_id_fkey1",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            "dossier_id",
            "piece_jointe_id",
            name="dossier_fichier_tableau_suivi_camion_citerne_assoc_last_sn_pkey",
        ),
    )
    op.create_index(
        "ix_dossier_fichier_tableau_suivi_camion_citerne_assoc_l_c63e",
        "dossier_fichier_tableau_suivi_camion_citerne_assoc_last_snapsho",
        ["date_created"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_dossier_fichier_tableau_suivi_camion_citerne_assoc_ls_date_created"),
        table_name="dossier_fichier_tableau_suivi_camion_citerne_assoc_ls",
    )
    op.drop_table("dossier_fichier_tableau_suivi_camion_citerne_assoc_ls")
    # ### end Alembic commands ###
