"""empty message

Revision ID: b0cbb7dd97ef
Revises: de7fc32e432c
Create Date: 2024-05-23 01:09:01.783002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0cbb7dd97ef'
down_revision: Union[str, None] = 'de7fc32e432c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece_jointe',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('type_fichier', sa.String(), nullable=True),
    sa.Column('nom_fichier', sa.String(), nullable=True),
    sa.Column('demande_simplifiees_url', sa.String(), nullable=True),
    sa.Column('object_storage_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piece_jointe_date_created'), 'piece_jointe', ['date_created'], unique=False)
    op.create_table('avis_assoc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('avis_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('piece_jointe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['avis_id'], ['avis.id'], ),
    sa.ForeignKeyConstraint(['piece_jointe_id'], ['piece_jointe.id'], ),
    sa.PrimaryKeyConstraint('id', 'avis_id', 'piece_jointe_id')
    )
    op.create_index(op.f('ix_avis_assoc_date_created'), 'avis_assoc', ['date_created'], unique=False)
    op.create_table('extraits_de_registres_assoc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('extrait_de_registre_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('piece_jointe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['extrait_de_registre_id'], ['extrait_de_registre.id'], ),
    sa.ForeignKeyConstraint(['piece_jointe_id'], ['piece_jointe.id'], ),
    sa.PrimaryKeyConstraint('id', 'extrait_de_registre_id', 'piece_jointe_id')
    )
    op.create_index(op.f('ix_extraits_de_registres_assoc_date_created'), 'extraits_de_registres_assoc', ['date_created'], unique=False)
    op.create_table('fichiers_autres_documents_assoc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('donnees_point_de_prelevement_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('piece_jointe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['donnees_point_de_prelevement_id'], ['donnees_point_de_prelevement.id'], ),
    sa.ForeignKeyConstraint(['piece_jointe_id'], ['piece_jointe.id'], ),
    sa.PrimaryKeyConstraint('id', 'donnees_point_de_prelevement_id', 'piece_jointe_id')
    )
    op.create_index(op.f('ix_fichiers_autres_documents_assoc_date_created'), 'fichiers_autres_documents_assoc', ['date_created'], unique=False)
    op.create_table('fichiers_tableurs_assoc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('donnees_point_de_prelevement_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('piece_jointe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['donnees_point_de_prelevement_id'], ['donnees_point_de_prelevement.id'], ),
    sa.ForeignKeyConstraint(['piece_jointe_id'], ['piece_jointe.id'], ),
    sa.PrimaryKeyConstraint('id', 'donnees_point_de_prelevement_id', 'piece_jointe_id')
    )
    op.create_index(op.f('ix_fichiers_tableurs_assoc_date_created'), 'fichiers_tableurs_assoc', ['date_created'], unique=False)
    op.create_table('message_assoc',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('piece_jointe_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['piece_jointe_id'], ['piece_jointe.id'], ),
    sa.PrimaryKeyConstraint('id', 'message_id', 'piece_jointe_id')
    )
    op.create_index(op.f('ix_message_assoc_date_created'), 'message_assoc', ['date_created'], unique=False)
    op.drop_column('avis', 'pieces_jointes')
    op.add_column('demarche_data_brute', sa.Column('object_storage_key', sa.String(), nullable=True))
    op.drop_constraint('demarche_data_brute_file_path_key', 'demarche_data_brute', type_='unique')
    op.create_unique_constraint(None, 'demarche_data_brute', ['object_storage_key'])
    op.drop_column('demarche_data_brute', 'file_path')
    op.drop_column('donnees_point_de_prelevement', 'fichier_tableur')
    op.drop_column('donnees_point_de_prelevement', 'fichier_autre_document')
    op.drop_column('extrait_de_registre', 'extrait_registre_papier')
    op.drop_column('message', 'pieces_jointes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('pieces_jointes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('extrait_de_registre', sa.Column('extrait_registre_papier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('donnees_point_de_prelevement', sa.Column('fichier_autre_document', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('donnees_point_de_prelevement', sa.Column('fichier_tableur', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('demarche_data_brute', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'demarche_data_brute', type_='unique')
    op.create_unique_constraint('demarche_data_brute_file_path_key', 'demarche_data_brute', ['file_path'])
    op.drop_column('demarche_data_brute', 'object_storage_key')
    op.add_column('avis', sa.Column('pieces_jointes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_message_assoc_date_created'), table_name='message_assoc')
    op.drop_table('message_assoc')
    op.drop_index(op.f('ix_fichiers_tableurs_assoc_date_created'), table_name='fichiers_tableurs_assoc')
    op.drop_table('fichiers_tableurs_assoc')
    op.drop_index(op.f('ix_fichiers_autres_documents_assoc_date_created'), table_name='fichiers_autres_documents_assoc')
    op.drop_table('fichiers_autres_documents_assoc')
    op.drop_index(op.f('ix_extraits_de_registres_assoc_date_created'), table_name='extraits_de_registres_assoc')
    op.drop_table('extraits_de_registres_assoc')
    op.drop_index(op.f('ix_avis_assoc_date_created'), table_name='avis_assoc')
    op.drop_table('avis_assoc')
    op.drop_index(op.f('ix_piece_jointe_date_created'), table_name='piece_jointe')
    op.drop_table('piece_jointe')
    # ### end Alembic commands ###
