"""empty message

Revision ID: d63fdf68a0af
Revises:
Create Date: 2024-05-04 00:03:04.767137

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d63fdf68a0af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demarche_data_brute",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("hashed_collected_data", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("demarche_number", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
        sa.UniqueConstraint("hashed_collected_data"),
    )
    op.create_index(
        op.f("ix_demarche_data_brute_date_created"),
        "demarche_data_brute",
        ["date_created"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_demarche_data_brute_date_created"), table_name="demarche_data_brute"
    )
    op.drop_table("demarche_data_brute")
    # ### end Alembic commands ###
