"""empty message

Revision ID: de7fc32e432c
Revises: 47951e564f1b
Create Date: 2024-05-21 10:03:23.426309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de7fc32e432c'
down_revision: Union[str, None] = '47951e564f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avis',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('id_dossier', sa.Integer(), nullable=True),
    sa.Column('id_avis', sa.String(), nullable=True),
    sa.Column('demarche_data_brute_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('reponse', sa.String(), nullable=True),
    sa.Column('date_question', sa.DateTime(), nullable=True),
    sa.Column('date_reponse', sa.DateTime(), nullable=True),
    sa.Column('claimant_email', sa.String(), nullable=True),
    sa.Column('expert_email', sa.String(), nullable=True),
    sa.Column('pieces_jointes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['demarche_data_brute_id'], ['demarche_data_brute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avis_date_created'), 'avis', ['date_created'], unique=False)
    op.create_table('message',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('id_dossier', sa.Integer(), nullable=True),
    sa.Column('id_message', sa.String(), nullable=True),
    sa.Column('demarche_data_brute_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('pieces_jointes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['demarche_data_brute_id'], ['demarche_data_brute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_date_created'), 'message', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_date_created'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_avis_date_created'), table_name='avis')
    op.drop_table('avis')
    # ### end Alembic commands ###
